
# This file provides configuration for the project
project_id = "qyjjbpyqxwrluhymvshn"

[functions.email-integration]
verify_jwt = true

[[functions.email-integration.routes]]
path = "/"
method = ["GET", "POST", "OPTIONS"]

[[functions.email-integration.routes]]
path = "/connect"
method = ["POST", "OPTIONS"]

[[functions.email-integration.routes]]
path = "/disconnect"
method = ["POST", "OPTIONS"]

[[functions.email-integration.routes]]
path = "/oauth-callback"
method = ["POST", "OPTIONS"]
