
# This file provides configuration for the function
project_id = "qyjjbpyqxwrluhymvshn"

[functions.email-integration]
verify_jwt = true

[[functions.email-integration.routes]]
path = "/"
method = "POST"
