
# This file provides configuration for the function
project_id = "qyjjbpyqxwrluhymvshn"

[functions.email-integration]
verify_jwt = true

[[functions.email-integration.routes]]
path = "/"
method = "POST"

[[functions.email-integration.routes]]
path = "/connect"
method = "POST"

[[functions.email-integration.routes]]
path = "/disconnect"
method = "POST"

[[functions.email-integration.routes]]
path = "/oauth-callback"
method = "POST"
