
project_id = "qyjjbpyqxwrluhymvshn"

[api]
enabled = true
port = 8080
schemas = ["public", "storage", "graphql_public"]

[db]
port = 5432

[studio]
port = 3000

[inbucket]
port = 4000

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
enabled = true

[functions.xero-integration]
verify_jwt = true

[functions.myob-integration]
verify_jwt = true
