
import { useState } from "react";
import { JobType } from "@/types/job";

const defaultJob: JobType = {
  id: "", // Will be generated by database, kept as empty string for form
  customer: "",
  vehicle: "",
  service: "",
  status: "pending",
  assignedTo: "",
  date: new Date().toISOString().split('T')[0],
  time: "09:00",
  timeEstimate: "1 hour",
  priority: "Medium",
  duration: 60,
  customerPhone: "",
  customerEmail: "",
  notes: ""
};

export const useJobForm = (initialJob: JobType = defaultJob) => {
  const [job, setJob] = useState<JobType>(initialJob);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setJob((prev) => ({ ...prev, [name]: value }));
  };

  const handleSelectChange = (name: string, value: string) => {
    setJob((prev) => ({ ...prev, [name]: value }));
  };

  const resetForm = () => {
    setJob({...defaultJob});
  };

  // UUIDs are now auto-generated by Supabase
  const getJobWithId = () => {
    return job as JobType; // id will be generated by database
  };

  return {
    job,
    setJob,
    handleChange,
    handleSelectChange,
    resetForm,
    getJobWithId
  };
};
