
# This file provides configuration for the function
project_id = "qyjjbpyqxwrluhymvshn"

[routes.{"/"}]
function = "functions/email-integration/index.ts"

[routes.{"/connect"}]
function = "functions/email-integration/connect.ts"

[routes.{"/disconnect"}]
function = "functions/email-integration/disconnect.ts"
