// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyjjbpyqxwrluhymvshn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5ampicHlxeHdybHVoeW12c2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNzgwNjgsImV4cCI6MjA1Nzg1NDA2OH0.VByO7baQVLDg1782zsaSeigpByOgD3XizEzONNsVgtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);